name: ecommerce_bts
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  super_bottom_navigation_bar: ^1.0.0
  top_modal_sheet: ^2.0.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  http: ^1.1.0
  shimmer: ^3.0.0
  add_to_cart_animation: ^2.0.3
  cached_network_image: ^3.3.1
  easy_search_bar: ^2.5.0
  audioplayers: ^5.2.1
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  awesome_snackbar_content: ^0.1.3
  google_places_autocomplete_text_field: ^0.1.3
  google_places_flutter: ^2.0.8
  progress_dialog2: ^1.0.0
  flutter_email_sender: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
      - assets/images/
    #   - images/a_dot_ham.jpeg

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
