// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv4q-TtveuMZMeNL6xInPBtoqvIR8DbYc',
    appId: '1:764891173644:web:f219de8348db799a2d2f29',
    messagingSenderId: '764891173644',
    projectId: 'ecommerce-bts',
    authDomain: 'ecommerce-bts.firebaseapp.com',
    storageBucket: 'ecommerce-bts.appspot.com',
    measurementId: 'G-QC64C8RB67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaJ2ivp15asymgWbJmsxyKRPau4WwSnw',
    appId: '1:764891173644:android:2abf5f9ade5454582d2f29',
    messagingSenderId: '764891173644',
    projectId: 'ecommerce-bts',
    storageBucket: 'ecommerce-bts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaSfjq7syRuk4j7rPKbxI0JWHdVysWyM',
    appId: '1:764891173644:ios:315ec6bd87384b7b2d2f29',
    messagingSenderId: '764891173644',
    projectId: 'ecommerce-bts',
    storageBucket: 'ecommerce-bts.appspot.com',
    iosBundleId: 'com.example.ecommerceBts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFaSfjq7syRuk4j7rPKbxI0JWHdVysWyM',
    appId: '1:764891173644:ios:c4727b4612e9d6eb2d2f29',
    messagingSenderId: '764891173644',
    projectId: 'ecommerce-bts',
    storageBucket: 'ecommerce-bts.appspot.com',
    iosBundleId: 'com.example.ecommerceBts.RunnerTests',
  );
}
